# Generated by Django 5.0.2 on 2024-09-12 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/avatars/', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Property Title')),
                ('slug', models.SlugField(allow_unicode=True, default='slug')),
                ('postcode', models.CharField(default='140', max_length=100, verbose_name='Postcode')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('advert_type', models.CharField(choices=[('For Sale', 'For Sale'), ('To Rent', 'To Rent')], default='For Sale', max_length=50, verbose_name='Advert Type')),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Flat / Apartment', 'Flat / Apartment'), ('Office', 'Office'), ('Bungalow', 'Bungalow'), ('Warehouse', 'Warehouse'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='House', max_length=50, verbose_name='Property Type')),
                ('plot_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Plot Area(m^2)')),
                ('total_floors', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='1', max_length=50, verbose_name='Total Floors')),
                ('bedrooms', models.CharField(choices=[('Studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='1', max_length=50, verbose_name='Bedrooms')),
                ('bathrooms', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='1', max_length=50, verbose_name='bathrooms')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='static/images/properties/', verbose_name='Main Photo')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='static/images/properties/', verbose_name='Photo 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='static/images/properties/', verbose_name='Photo 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='static/images/properties/', verbose_name='Photo 3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='static/images/properties/', verbose_name='Photo 4')),
                ('published_status', models.BooleanField(default=False, verbose_name='Published Status')),
                ('ref_code', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Property Reference Code')),
                ('views', models.IntegerField(default=0, verbose_name='Total Views')),
                ('description', models.TextField(default='Add description here...', verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='cities_light.city', verbose_name='City / Town')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Listed by')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
