# Generated by Django 4.1.7 on 2024-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0002_alter_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_gt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price_gt'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_lt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Price_lt'),
        ),
    ]
