# Generated by Django 5.0.2 on 2024-04-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0002_alter_property_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yourhome.user', verbose_name='Listed by'),
        ),
    ]
