# Generated by Django 4.1.7 on 2024-02-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0003_property_price_gt_property_price_lt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price_gt',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_lt',
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
