# Generated by Django 4.1.7 on 2024-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0004_remove_property_price_gt_remove_property_price_lt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='advert_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('To Rent', 'To Rent')], default='For Sale', max_length=50, verbose_name='Advert Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default='1', max_length=50, verbose_name='bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('Studio', 'Studio'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default='1', max_length=50, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default='0', max_length=50, verbose_name='Total Floors'),
        ),
    ]
