# Generated by Django 5.0.2 on 2024-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0005_alter_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
