# Generated by Django 4.1.7 on 2024-03-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0005_alter_property_advert_type_alter_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default='1', max_length=50, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Any', 'Any'), ('House', 'House'), ('Flat / Apartment', 'Flat / Apartment'), ('Office', 'Office'), ('Bungalow', 'Bungalow'), ('Warehouse', 'Warehouse'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='Any', max_length=50, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default='1', max_length=50, verbose_name='Total Floors'),
        ),
    ]
