# Generated by Django 4.1.7 on 2024-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0006_alter_property_bedrooms_alter_property_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Flat / Apartment', 'Flat / Apartment'), ('Office', 'Office'), ('Bungalow', 'Bungalow'), ('Warehouse', 'Warehouse'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='House', max_length=50, verbose_name='Property Type'),
        ),
    ]
