# Generated by Django 5.0.2 on 2024-04-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0007_remove_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
