# Generated by Django 5.0.2 on 2024-04-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0010_alter_user_avatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/avatars/', verbose_name='Profile Picture'),
        ),
    ]
