# Generated by Django 5.0.2 on 2024-03-13 16:55

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0010_remove_property_country_address_alter_property_city'), 
    ]

    operations = []