# Generated by Django 5.0.2 on 2024-03-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
     
        ('yourhome', '0011_auto_20240313_1655'),
    ]

    operations = [
    ]
