# Generated by Django 5.0.2 on 2024-03-13 17:10

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
    
        ('yourhome', '0009_property_country'), 
    ]

    operations = []