# Generated by Django 5.0.2 on 2024-03-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0013_property_country_alter_property_city'),
        ('yourhome', '0014_auto_20240313_1710'),
    ]

    operations = [
    ]
