# Generated by Django 5.0.2 on 2024-03-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('yourhome', '0015_merge_20240313_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country'),
        ),
    ]
