# Generated by Django 5.0.2 on 2024-03-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourhome', '0016_alter_property_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='1', max_length=50, verbose_name='bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='1', max_length=50, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default='1', max_length=50, verbose_name='Total Floors'),
        ),
    ]
